import { useState, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";

import { logo } from "@/public/assets/images";

import { motion } from "framer-motion";

import {
  Navbar,
  LeftSide,
  RightSide,
  Banner,
  About,
  Experience,
  Projects,
  Archive,
  Contact,
  Footer,
} from "../components";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    const timer = setInterval(() => {
      setIsLoading(false);
    }, 3000);
    return () => clearInterval(timer);
  }, []);
  return (
    <>
      <Head>
        <title>Hazem Hussein</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      {isLoading ? (
        <div className="grid w-full h-screen bg-bodyColor place-items-center">
          <div className="spinner">
            <Image src={logo} alt="logo" />
          </div>
        </div>
      ) : (
        <main className="w-full h-screen overflow-x-hidden overflow-y-scroll font-bodyFont bg-bodyColor text-textLight">
          <Navbar />
          <div className="w-full h-[88vh] xl:flex items-center gap-20  justify-between">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5 }}
              className="fixed bottom-0 left-0 hidden w-32 h-full xl:inline-flex"
            >
              <LeftSide />
            </motion.div>
            <div className="h-[88vh] w-full mx-auto p-4">
              <Banner />
              <About />
              <Experience />
              <Projects />
              <Archive />
              <Contact />
              <Footer />
            </div>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5 }}
              className="fixed bottom-0 right-0 hidden w-32 h-full xl:inline-flex"
            >
              <RightSide />
            </motion.div>
          </div>
        </main>
      )}
    </>
  );
}
